# Copyright (C) 2023 Remy Cases
# See LICENSE file for extended copyright information.
# This file is part of adventOfCode project from https://github.com/remyCases/adventOfCode.

[workspace]
members = [
	"utils/rust_utils"
]

[workspace.dependencies]

[package]
name = "AdventOfCodeRust"
version = "0.2.0"
authors = ["RémyCases"]
edition = "2021"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7" }
gcd = { version = "2" }
aoc_utils = { path = "utils/rust_utils" }

[profile.Release]
inherits = "release"

[profile.Dev]
inherits = "dev"

