>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. MAINCOB.
AUTHOR. RémyCases

ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 Woption.
       02 WDay PIC 9.
       02 WPart PIC 9.
01 Wword PIC X(80).

PROCEDURE DIVISION.
Main.
       ACCEPT Woption FROM COMMAND-LINE
       
       IF WDay EQUAL TO 1 THEN
           CALL '2022/lib/DAYONE' USING WPart
       END-IF

       IF WDay EQUAL TO 2 THEN
           CALL '2022/lib/DAYTWO' USING WPart
       END-IF

       IF WDay EQUAL TO 3 THEN
           CALL '2022/lib/DAYTHREE' USING WPart
       END-IF

       IF WDay EQUAL TO 4 THEN
           CALL '2022/lib/DAYFOUR' USING WPart
       END-IF
       
       MOVE "9GTRW GCHPMSVW CLTSGM JHDMWRF PQLHSWFJ PJDNFMS ZBDFGCSJ RTB HNWLC" TO Wword
       IF WDay EQUAL TO 5 THEN
           CALL '2022/lib/DAYFIVE' USING Wword
       END-IF
       STOP RUN.
