>>SOURCE FORMAT FREE
IDENTIFICATION DIVISION.
PROGRAM-ID. MAINCOB.
AUTHOR. RémyCases

ENVIRONMENT DIVISION.
DATA DIVISION.
WORKING-STORAGE SECTION.
01 Woption.
       02 WDay PIC 9.
       02 WPart PIC 9.

PROCEDURE DIVISION.
Main.
       ACCEPT Woption FROM COMMAND-LINE
       
       IF WDay EQUAL TO 1 THEN
           CALL '2022/lib/DAYONE' USING WPart
       END-IF
       STOP RUN.
